name: Automatically crawl CVEs
on:
#   schedule:
#     - cron:  '10 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Crawl CVEs
      env:
          CRAWL_URL: ${{ secrets.CRAWL_URL }}
          URL_LIST: ${{ secrets.URL_LIST }}
          URL_CVE: ${{ secrets.URL_CVE }}
      run: |-
        python main.py -gtk ${{ secrets.GITHUB_TOKEN }}
#         python main.py -gtk ${{ secrets.GITHUB_TOKEN }}
    # 若该时间段没有 CVE， 则 file://cache/mail.dat 文件不会生成，此时不会发送邮件
    - name: Send mail
      uses: Mr-xn/action-send-mail@master
      with:
        server_address: ${{ secrets.MAIL_SMTP }}
        server_port: 587
        username: ${{ secrets.MAIL_USER }}
        password: ${{ secrets.MAIL_PASS }}
        from: ${{ secrets.MAIL_USER }}
        to: file://cache/mail_recvs.dat # ${{ secrets.MAIL_RECV }}
        subject: 威胁情报播报
        body: file://cache/mail_content.dat
        content_type: text/html

    # readme-bot 是 Github runner 的固定账号，不用改
    - name: Commit and push Github page (if changed)
      run: |-
        git init
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated by Github Robot" || exit 0
        git push
